name: ci
on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-version: ['7.4', '8.0']
        composer-prefer-lowest: [false]
        include:
          - operating-system: 'ubuntu-latest'
            php-version: '7.4'
            composer-prefer-lowest: true

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          #coverage: xdebug

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install PHIVE
        uses: szepeviktor/phive@v1
        with:
          home: "${{ runner.temp }}/.phive"
          binPath: "${{ github.workspace }}/tools/phive"

      - name: Start PHIVE manually
        run: "${{ github.workspace }}/tools/phive --no-progress install --trust-gpg-keys 4AA394086372C20A,31C7E470E2138192,CF1A108D0E7AE720"

      - name: Install Composer dependencies
        if: matrix.composer-prefer-lowest == false
        run: composer update

      - name: Install lowest Composer dependencies
        if: matrix.composer-prefer-lowest == true
        run: composer update --prefer-lowest

      - name: Codesniffer
        run: composer run-script cs-check

      - name: Static code analysis
        run: composer run-script analyze
